name: Xous-Precursor tests
on:
  push:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare xous dependencies
        run: sudo apt install curl -y
      - name: Build Xous
        run: ./build-xous.sh
        shell: bash
      - name: Run tests
        uses: antmicro/renode-test-action@v1.0.0
        with:
            renode-version: 'latest'
            tests-to-run: 'xous.robot'
      - name: Archive tests results
        uses: actions/upload-artifact@v2
        with:
            name: test-results
            path: |
                report.html
                log.html
                robot_output.xml
