name: Xous-Precursor tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare xous dependencies
        run: |
            sudo apt install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - name: Build xous-precursor renode image
        run: ./prepare_image.sh
        shell: bash
      - name: Copy testing resc file to a proper folder
        run: cp xous.resc xous-core/emulation/xous-test.resc
      - name: Run tests
        uses: antmicro/renode-test-action@v1.0.0
        with:
            renode-version: 'latest'
            tests-to-run: 'xous.robot'
      - name: Archive tests results
        uses: actions/upload-artifact@v2
        with:
            name: test-results
            path: |
                report.html
                log.html
                robot_output.xml
